### ISSUE TITLE
[0.99] Cannot read property 'exchange' of undefined

### ISSUE THREAD

**Issue by caogeoge** [Sjakil/gunthy-gui#20]
Hi Sjakil,

Everything was working fine since I upgraded to 0.99 except the last hour or so I got an exception of "TypeError: Cannot read property 'exchange' of undefined". I'm running 68 pairs with Diesel's settings on 1 x instance of GB and 1 x instance of Gunthy GUI:

2017-09-21 00:41:32: Client authenticated for IP: "::ffff:88.150.157.111"
TypeError: Cannot read property 'exchange' of undefined
    at /__enclose_io_memfs__/emitters.js:210:14
    at Array.forEach (<anonymous>)
    at Statement.<anonymous> (/__enclose_io_memfs__/emitters.js:204:20)
2017-09-21 00:41:33: Committing database transaction before quitting ...

**Comment by Sjakil** [comment]
It should now be taken care of (in release 0.991). Please let me know if you encounter this error again using that version.
