### ISSUE TITLE
Strange error msgs when trying to start Gunthy Gui

### ISSUE THREAD

**Issue by Azuia** [Sjakil/gunthy-gui#32]
Hello

I can get Gunthy gui to load and add pairs.  When i hit the Green G button to start.  I get the following error msgs

Gunbot started
Bot crashed at 2017/10/04 20:58:55
Reason: Failed to load config!!!
Parameter: undefined---color-config.js
Original error: { Error: Cannot find module '\gun bot\undefined---color-config.js'
at Module._resolveFilename (module.js:470:15)
at Function.Module._resolveFilename (evalmachine.:0:0)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at Module.require (evalmachine.:0:0)
at require (internal/module.js:20:19)
at loadConfig (evalmachine.:0:0)
at new Bot (evalmachine.:0:0)
at Object.console.C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\index.js.dev (evalmachine.:0:0)
at Module._compile (evalmachine.:0:0)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.runMain (evalmachine.:0:0)
at run (bootstrap_node.js:426:7)
at startup (bootstrap_node.js:147:9)
at bootstrap_node.js:541:3 code: 'MODULE_NOT_FOUND' }
Gunbot stopped

Any help fixing this problem would be great!

Thanks for the help

**Comment by AshtakM** [comment]
Hi, did you have any success resolving this error?
