### ISSUE TITLE
running on mac error

### ISSUE THREAD

**Issue by utdrmac** [Sjakil/gunthy-gui#4]
`npm install pm2@2.5.0 -g`

When attempting to turn on a bot, crashes:

```
/__enclose_io_memfs__/init.js:30
		throw err;
		^

TypeError: Cannot read property 'pm2_env' of null
    at /__enclose_io_memfs__/node_modules/pm2/lib/API.js:1045:86
    at /__enclose_io_memfs__/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/__enclose_io_memfs__/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at Parser._write (/__enclose_io_memfs__/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at Parser.Writable.write (_stream_writable.js:274:11)
    at Socket.ondata (_stream_readable.js:628:20)
```

**Comment by MathieuCassagne** [comment]
I got the same error, it is an issue with the permissions of gunthy-linx64, the binary is not executable.
